module.exports = {
  roots: ['./__tests__', './packages'],
  displayName: 'tests',
  testMatch: ['**/__tests__/**/*.test.js', '*.test.js'],
  testURL: 'http://localhost',
  transformIgnorePatterns: ['/node_modules/(?!@tecsinapse/ui-kit).+\\.js$'],
  transform: {
    '^.+\\.js$': 'babel-jest',
  },
  moduleDirectories: [
    'node_modules',
    'utils',
    'packages/wizard/src',
    'packages/uploader/src',
    'packages/ui-kit/src',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/packages/carousel/build/',
    '<rootDir>/packages/carousel/stories/',
    '<rootDir>/packages/pickers/build/',
    '<rootDir>/packages/pickers/stories/',
    '<rootDir>/packages/table/build/',
    '<rootDir>/packages/table/stories/',
    '<rootDir>/packages/ui-kit/build/',
    '<rootDir>/packages/ui-kit/stories/',
    '<rootDir>/packages/uploader/build/',
    '<rootDir>/packages/uploader/stories/',
    '<rootDir>/packages/wizard/build/',
    '<rootDir>/packages/wizard/stories/',
  ],
};
