import { grey } from '@material-ui/core/colors';

export const defaultGreen = '#4caf50';
export const defaultGreenDarker = '#448744';
export const defaultRed = '#e6433f';
export const defaultRedDarker = '#af423e';
export const defaultOrange = '#ff9d0d';
export const defaultOrangeDarker = '#cd6e0d';
export const defaultGrey = grey[700];
export const defaultGrey2 = '#787879';
export const defaultGreyLight = grey[500];
export const defaultGreyLight2 = grey[600];
export const defaultGreyLight3 = '#f7f7f7';
export const defaultGreyLight200 = grey[200];
export const defaultGreyDisabled = grey[400];
export const defaultGreyLight4 = '#f2f2f2';
export const defaultGreyLight5 = '#B2B2B2';
export const defaultGreyDark = '#817e7d';
export const defaultWhite = '#ffffff';
export const defaultBlack = '#000';
export const defaultBlue = '#003473';
export const defaultYellow = '#ffed00';
export const defaultBadgeColor = '#FD0051';
