name: UI Kit Release

on:
  workflow_dispatch:
    inputs:
      semantic_version:
        description: "Versão Semântica"
        required: true
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"
          - "from-package"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      NPM_REGISTRY_URL: "https://registry.npmjs.org/"

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Git
        shell: bash
        run: |
          git config --global user.email "git@tecsinapse.com.br"
          git config --global user.name "gitTecsinapse[bot]"

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: yarn

      - name: Instalar Dependências
        run: yarn install --frozen-lockfile

      - name: Configurar Token do NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "${NPM_REGISTRY_URL#https:}:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc

      - name: Validar autenticação no NPM
        run: npm whoami --registry="${NPM_REGISTRY_URL}"

      - name: Publicar com Lerna
        run: |
          if [ "${{ inputs.semantic_version }}" = "from-package" ]; then
            npx lerna publish from-package --yes --no-verify-access --registry="${NPM_REGISTRY_URL}"
          else
            npx lerna publish ${{ inputs.semantic_version }} --yes --no-verify-access --conventional-commits --registry="${NPM_REGISTRY_URL}"
          fi

      - name: Remover arquivo .npmrc
        if: always()
        run: rm ~/.npmrc
